
# Main Colors
unrecognized_file: "#45707a"
recognized_file:   "#4c7a5d"
executable_file:   "#6c782e"
dir:               "#c35e0a"

# Link
dead_link: "#c14a4a"
link:      "#4c7a5d"

# special files
socket:    "#6c782e"
blockdev:  "#6c782e"
chardev:   "#6c782e"

# Access Modes
write:     "#45707a"
read:      "#945e80"
exec:      "#b85f3d"
no_access: "#8d877d"

# Age
day_old:     "#945e80"
hour_old:    "#a84b3a"
no_modifier: "#a9a39a"

# File Size
file_large:  "#c35e0a"
file_medium: "#b47109"
file_small:  "#6b665f"

# Random
report: "#654735"
user:   "#45707a"
tree:   "#a9a39a"
empty:  "#b47109"
error:  "#c14a4a"
normal: "#4f3829"
inode:  "#45707a"

# Git
addition:     "#6c782e"
modification: "#b47109"
deletion:     "#c14a4a"
untracked:    "#c35e0a"
unchanged:    "#4c7a5d"