# Main Colors
unrecognized_file: cadetblue
recognized_file:   deepskyblue
executable_file:   darkturquoise
dir:               fuchsia

# Link
dead_link: red
link:      cyan

# special files
socket:    green
blockdev:  green
chardev:   green

# Access Modes
write:     royalblue
read:      magenta
exec:      deeppink
no_access: dimgray

# Age
day_old:     blueviolet
hour_old:    darkviolet
no_modifier: violet

# File Size
file_large:  orange
file_medium: gold
file_small:  peachpuff

# Random
report: white
user:   darkslateblue
tree:   cyan
empty:  yellow
error:  red
normal: darkkhaki
inode:  blue

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
