# Main Colors
unrecognized_file: indigo
recognized_file:   mediumslateblue
executable_file:   mediumvioletred
dir:               rebeccapurple

# Link
dead_link: firebrick
link:      slateblue

# Special files
socket:    darkmagenta
blockdev:  darkslateblue
chardev:   peru

# Access Modes
write:     purple
read:      darkorchid
exec:      crimson
no_access: dimgray

# Age
day_old:     darkorchid
hour_old:    indianred
no_modifier: darkviolet

# File Size
file_large:  darkred
file_medium: sienna
file_small:  peru

# Misc
report: mediumpurple
user:   indigo            # controls BOTH owner & group columns
tree:   slateblue
empty:  goldenrod
error:  firebrick
normal: darkslategray     # darker base to avoid blending
inode:  darkorchid

# Git
addition:     seagreen
modification: mediumorchid
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
