# Main Colors
unrecognized_file: blue
recognized_file:   darkcyan
executable_file:   red
dir:               fuchsia

# Link
dead_link: red
link:      cyan

# special files
socket:    darkgray
blockdev:  darkgray
chardev:   darkgray

# Access Modes
write:     royalblue
read:      magenta
exec:      deeppink
no_access: dimgray

# Age
day_old:     red
hour_old:    coral
no_modifier: darkviolet

# File Size
file_large:  red
file_medium: coral
file_small:  darkgray

# Random
report: darkviolet
user:   darkblue
tree:   cyan
empty:  yellow
error:  red
normal: darkgray
inode:  violet

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    darkgreen
