# Main Colors
unrecognized_file: darkred
recognized_file:   darkgreen
executable_file:   green
dir:               navyblue

# Link
dead_link: red
link:      cyan

# special files
socket:    darkgray
blockdev:  darkgray
chardev:   darkgray

# Access Modes
write:     red
read:      sienna
exec:      navyblue
no_access: darkviolet

# Age
day_old:     red
hour_old:    coral
no_modifier: darkviolet

# File Size
file_large:  red
file_medium: coral
file_small:  darkgray

# Random
report: darkviolet
user:   darkblue
tree:   cyan
empty:  yellow
error:  red
normal: darkgray
inode: violet

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    darkgreen
