-- Gruvbox Material theme — rendered via catppuccin with full color overrides.
-- Color overrides are generated by interdotensional into vim.g.catppuccin_overrides.
local utils = require('utils')
local current_theme = vim.g.colorscheme.theme

local color_overrides = {
  [current_theme] = vim.g.catppuccin_overrides,
}

local palette = utils.get_palette("catppuccin", current_theme)
for key, value in pairs(color_overrides[current_theme]) do
  palette[key] = value
end

require('ui.colors').initialize_colors(palette)
local colors = vim.g.colors

local borderless = vim.g.border == "none"

require('catppuccin').setup({
  flavour = current_theme,
  transparent_background = false,
  show_end_of_buffer = false,
  term_colors = false,
  dim_inactive = {
    enabled = false,
    shade = "dark",
    percentage = 0.15,
  },
  no_italic = false,
  no_bold = false,
  no_underline = false,
  styles = {
    comments = { "italic" },
    conditionals = {},
    loops = {},
    functions = {},
    keywords = {},
    strings = {},
    variables = {},
    numbers = {},
    booleans = {},
    properties = {},
    types = {},
    operators = {},
    miscs = {}, -- add this to prevent "italic" on modules/attributes/references etc.
  },
  lsp_styles = {
    inlay_hints = {
      background = false,
    }
  },
  color_overrides = color_overrides,
  custom_highlights = {
    WinSeparator                = { fg = colors.light_bg },
    TabLineSel                  = { bg = colors.accent },

    FloatBorder                 = utils.ternary(borderless, { fg = colors.alt_bg, bg = colors.alt_bg }, { fg = colors.light_bg, bg = colors.none }),
    FloatTitle                  = utils.ternary(borderless, { fg = colors.alt_fg, bg = colors.alt_bg }, { fg = colors.light_bg, bg = colors.none }),
    NormalFloat                 = utils.ternary(borderless, {}, { bg = colors.none }),

    PmenuSel                    = { bg = colors.alt_fg, style = {} },

    BlinkCmpLabelDescription    = { fg = colors.comment, style = { "italic" } },

    NoicePopup                  = { bg = colors.dark_bg },
    NoiceCmdlinePopupBorder     = utils.ternary(borderless, { fg = colors.light_bg, bg = colors.bg }, { fg = colors.light_bg }),
    NoiceCmdlinePopup           = utils.ternary(borderless, { bg = colors.light_bg }, {}),

    StatusLine                  = { fg = colors.bg, bg = colors.bg },
    StatusLineNC                = { fg = colors.bg, bg = colors.bg },

    CursorLineNr                = { fg = colors.accent, style = { "bold" } },

    OutlineCurrent              = { fg = colors.orange, bg = "", style = { "bold" } },

    -- Telescope
    TelescopeNormal             = { fg = colors.fg, bg = colors.dark_bg },
    TelescopeBorder             = { fg = colors.dark_bg, bg = colors.dark_bg },
    TelescopePromptNormal       = { fg = colors.fg, bg = colors.light_bg },
    TelescopePromptBorder       = { fg = colors.light_bg, bg = colors.light_bg },
    TelescopePromptTitle        = { fg = colors.light_bg, bg = colors.red },
    TelescopeResultsTitle       = { fg = colors.alt_fg, bg = colors.purple },
    TelescopeResultsNormal      = { fg = colors.fg, bg = colors.dark_bg },
    TelescopeResultsBorder      = { fg = colors.dark_bg, bg = colors.dark_bg },
    TelescopePreviewTitle       = { fg = colors.light_bg, bg = colors.green },
    TelescopeMatching           = { fg = colors.orange, style = { "bold" } },
    TelescopeDirectoryCustom    = { fg = colors.comment },

    NvimTreeFolderName          = { fg = colors.orange },
    NvimTreeFolderIcon          = { fg = colors.orange },
    NvimTreeOpenedFolderName    = { fg = colors.orange },
    NvimTreeEmptyFolderName     = { fg = colors.orange },
    NvimTreeIndentMarker        = { fg = colors.comment },
    NvimTreeRootFolder          = { fg = colors.orange, style = { "bold" } },
    NvimTreeSymlink             = { fg = colors.pink },
    NvimTreeGitDirty            = { fg = colors.yellow },
    NvimTreeGitNew              = { fg = colors.blue },
    NvimTreeGitDeleted          = { fg = colors.red },
    NvimTreeSpecialFile         = { fg = colors.orange },
    NvimTreeImageFile           = { fg = colors.fg },
    NvimTreeNormal              = { bg = colors.alt_bg },
    NvimTreeNormalNC            = { bg = colors.alt_bg },
    NvimTreeExecFile            = { fg = colors.red },

    TreesitterContext           = { bg = colors.bg },
    TreesitterContextBottom     = { sp = vim.g.neovide and colors.bg or colors.light_bg, style = { "underline" } },

    ["@parameter.readonly"]     = { fg = colors.orange, style = { "italic" } },
    ["@parameter.modification"] = { fg = colors.orange, style = { "italic" } },

    DapBreakpoint               = { fg = colors.red },
    DapStopped                  = { fg = colors.green },

    GitSignsCurrentLineBlame    = { fg = colors.comment, style = { "italic" } },
    GitSignsCurrentLineBlameSep = { fg = colors.orange },

    NotifyERRORTitle            = { fg = colors.red, style = {} },
    NotifyWARNTitle             = { fg = colors.yellow, style = {} },
    NotifyINFOTitle             = { fg = colors.blue, style = {} },
    NotifyDEBUGTitle            = { fg = colors.orange, style = {} },
    NotifyTRACETitle            = { fg = colors.pink, style = {} },

  },
  default_integrations = false,
  integrations = {
    cmp = true,
    blink_cmp = true,
    gitsigns = true,
    nvimtree = false,
    flash = true,
    lsp_trouble = true,
    markview = true,
    notify = true,
    mini = {
      enabled = true,
      indentscope_color = "",
    },
    snacks = true,
    treesitter = true,
  },
})
