[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss14"

[buildPlans.IosevkaCustom.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaCustom.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaCustom.widths.Extended]
shape = 600
menu = 7
css = "expanded"
